#pragma once
#include <Windows.h>
#include <string>
#include <exception>
#include <memory>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <DirectXMath.h>
#include <DirectXColors.h>
#include <wrl.h>
#include "resource.h"